name: Hello
#runson a trigger
on:
  push:
    branches: [dev]

jobs:

  github-action-job:
  runs-on: ubuntu-latest
    steps:
      - name: namaskar dosto
        run: echo "hello Friends"
      -name: say hello to user
        run:echo "hello$USER"
